spring:
  application:
    name: dept-service
  datasource:
    url: jdbc:mysql://localhost:3306/dept_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql






  cloud:
    config:
      enabled: false

    discovery:
      enabled: false

server:
  port: 9091


